import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './provider'
import { Montserrat, Inter, Playfair_Display, Signika_Negative } from 'next/font/google'

const inter = Inter({
   subsets: ['latin'] 
  })

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-monsterrat',
})

const playfair_Display = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
})

const signika_Negative = Signika_Negative({
  variable: '--font-signika-negative',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`bg-black text-text ${montserrat.variable} ${playfair_Display.variable} ${signika_Negative.variable} ${inter.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
