export enum FilterType { 
    Angular = "Angular",
    React = "React",
    Typescript = "Typescript",
    NextJS = "NextJS",
    MongoDB = "MongoDB",
    Node = "Node",
    CSS = "CSS",
    Tailwind = "Tailwind",
    UIUX = "UI/UX",
    UnitTest = "Unit Test",
    SocketIO = "SocketIO",
    Scrum = "Scrum",
    E2E = "E2E",
    SQL = "SQL",
    JavaScript = "JavaScript",
    PHP = "PHP",
    CICD = "CI/CD",
    All = "All",
}